### ISSUE TITLE
Fails to Run on Ubuntu

### ISSUE THREAD

**Issue by nubbyninja** [Victor-IX/Blender-Launcher-V2#128]
**Describe the bug**
Unable to launch via double-click / Desktop
Launch via terminal produces error: 
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /tmp/_MEI9b5hdX/libz.so.1)
 
 We verified libc is installed. 

**To Reproduce**
Download Ubuntu version of Blender Launcher to Ubuntu. 
Extract to Desktop.
Attempt to run.

**Expected behavior**
Expected launcher to open.

**System (please complete the following information):**
 - Operation system: Latest version of Ubuntu
 - Blender Launcher version: Latest release ([v2.2.0](https://github.com/Victor-IX/Blender-Launcher-V2/releases/tag/v2.2.0))
 - Log file: Unsure how to retrieve.

**Additional context**
We've been using Blender Launcher on Windows 10/11 for quite some time, on 3 different Windows machines. My daughter runs Ubuntu and is following a lot of course content / tutorials etc which spread across a lot of different blender versions. 

Blender Launcher V2 helped me immensely with this, but attempting to launch on desktop via click or right-click/run does nothing. 
Launch With / Files and Run As Application failed as well. 

We may be missing some install steps / instructions?

**Comment by zeptofine** [comment]
Strange, those kinds of errors should only be affecting older versions of Ubuntu 🤔

Would you be willing to try and running it without the bundled executable? It simply requires python3.9.
```bash
# clone the repo
git clone https://github.com/Victor-IX/Blender-Launcher-V2
cd Blender-Launcher-V2
# create a virtual environment
python -m venv .venv
source .venv/bin/activate
# install the dependencies
python -m pip install -e .

# to run the project:
# python source/main.py

# to try to build it:
# sh scripts/build_linux.sh
```
Once the dependencies are installed, you don't have to install them again. you just need to activate the virtual environment and run source/main.py. This can be made into a simple script
```sh
source .venv/bin/activate
python source/main.py
```
Or you can try to build the executable using the `scripts/build_linux.sh` script

**Comment by nubbyninja** [comment]
No lies, some of this is a little over my head but I'll give it a shot.

**Comment by emanvidmaker** [comment]
I got this exact error on Pops OS but I realized i had it wrong. ** I fix it by downloading the UBUNTU version (Not the linux version)**

before i realized that i tried to building and up to`python source/main.py` and errored out 

```bash
Resources were not built! Run python build_style.py to build the style.
Traceback (most recent call last):
  File "/home/eman/Downloads/sources/Blender-Launcher-V2/source/main.py", line 35, in <module>
    setup_logging(
  File "/home/eman/Downloads/sources/Blender-Launcher-V2/source/utils/logger.py", line 41, in setup_logging
    file_handler = logging.handlers.RotatingFileHandler(log_path, maxBytes=max_bytes, backupCount=backup_count)
  File "/usr/lib/python3.10/logging/handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/usr/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/eman/.cache/Blender Launcher/blender-launcher.log'
```

the logger seems to error out. 

Anyway got it to work using the UBUNTU version and not the Linux version, posting this to help some future poor soul out.
