### ISSUE TITLE
Access Denied Error in Deleting Builds

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [Victor-IX/Blender-Launcher-V2#66]
Build can't be deleted even running at administrator. Not to say that in the past I don't need to run it as administrator.

**System (please complete the following information):**
 - Operating system: Windows-10-10.0.19045-SP0 64 Bits
 - Blender Launcher version: 2.0.24
 -LOG:
[2024-02-05 17:48:22,443:ERROR] [WinError 5] Access is denied: 'E:/Apps/Blender/daily/blender-4.1.0-alpha+main.8b827a5bb539-windows.amd64-release\\4.1\\python\\DLLs\\libcrypto-3.dll'
Traceback (most recent call last):
  File "modules\tasks.py", line 108, in run
  File "threads\remover.py", line 17, in run
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 624, in _rmtree_unsafe
  File "shutil.py", line 624, in _rmtree_unsafe
  File "shutil.py", line 624, in _rmtree_unsafe
  File "shutil.py", line 629, in _rmtree_unsafe
  File "shutil.py", line 627, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'E:/Apps/Blender/daily/blender-4.1.0-alpha+main.8b827a5bb539-windows.amd64-release\\4.1\\python\\DLLs\\libcrypto-3.dll'
[2024-02-05 17:48:22,446:ERROR] [WinError 5] Access is denied: 'E:/Apps/Blender/daily/blender-4.1.0-alpha+main.8b827a5bb539-windows.amd64-release\\4.1\\python\\DLLs\\libcrypto-3.dll'

**Comment by Victor-IX** [comment]
Can you try to delete the build directly in the source folder? `E:/Apps/Blender/daily/`

**Comment by Gerstmann-Bradley** [comment]
Thanks, I tried yesterday, somehow it says it's opened in other app even after I turned off all blender and blender launchers. I restarted computer and I have no problem now. not sure why those happens.
