### ISSUE TITLE
Failed to execute script Imainl due to un exception: Failed to parse: http://255.255.255.255:99999

### ISSUE THREAD

**Issue by flyinggoatman** [Victor-IX/Blender-Launcher-V2#86]
**Describe the bug**
I was having some errors trying to get the newest patches so I tried adjusting some settings. After I changed this, the program refuses to open. I can't find a config to undo the change and reset the software.

**To Reproduce**
1. disable proxies
2. run program

**Expected behavior**
the program to open

**Screenshots**
<img width="251" alt="Blender_Launcher_dKsrMHnmGU" src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/3386066/981d2208-e487-496c-81f7-4528ea41a8b2">

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v2.0.24
 - Error Log
 Traceback (most recent call last):
  File "source\main.py", line 93, in <module>
  File "source\main.py", line 83, in main
  File "windows\main_window.py", line 96, in __init__
  File "windows\base_window.py", line 29, in __init__
  File "modules\connection_manager.py", line 103, in setup
  File "urllib3\poolmanager.py", line 478, in __init__
  File "urllib3\util\url.py", line 397, in parse_url
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://255.255.255.255:99999

 

**Additional context**
I'm stupid for disabling proxies.

**Comment by Victor-IX** [comment]
_Issue was resolved on discord_
## Solution :
Delete the proxy settings in the Blender Launcher.ini file to reset the proxy settings
